allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  e97210c8-7dcc-472a-bdad-9cadf9b9d9af:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-02-17T15:15:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dc07f9c1-877d-47a4-ab4d-93c2777e2794
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-17T21:35:07+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: daa155fe-6bef-4cf5-b0b5-abc213a997f0 # Erinnerung
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41e1315b-41c3-473e-b6da-9bccc46ce518
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-17T15:19:32+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ce171fd0-e71b-4ed1-9b30-0129366ada4c # Beschreibung
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c216638-cf3d-4fcb-8044-5000bd410c22
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-17T15:19:32+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 758983ef-8e21-411c-9414-d9e34779590d # Datum
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67abab2c-5330-4eb0-964d-c1c16c7329d6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-17T15:19:32+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: dfef2e4f-02bd-401a-a747-b23a7e124ed3 # Status
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a042ab3f-e0ae-4c85-a975-f9fea94d0f0a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-17T22:25:37+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f06fbcc3-85e9-4fe6-995a-68f8a2c2849f # Erledigt
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8246fea-073f-405a-ba25-183a5cedbdd1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a75144ac-737f-42af-b306-39cd4624da45
        userCondition: null
    thumbFieldKey: null
handle: default
hasTitleField: true
icon: null
name: Deafult
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
