columnSuffix: null
handle: erinnerung
instructions: null
name: Erinnerung
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - '1 Tag'
        -
          - value
          - 1Tag
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2 tage'
        -
          - value
          - 2Tage
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '3 Tage'
        -
          - value
          - 3Tage
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '4 Tage'
        -
          - value
          - 4Tage
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '1 Woche'
        -
          - value
          - 1Woche
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2 Wochen'
        -
          - value
          - 2Wochen
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
